### ISSUE TITLE
Ubuntu install still failing on farmers in 1.2.90

### ISSUE THREAD

**Issue by Qwinn1** [Apple-Network/apple-blockchain#18]
The same "MAC check failed" error that is described in Issue #16 is still happening trying to run apple 1.2.90 on a farmer in Ubuntu.  Installs fine on harvesters, but I still have to run 1.2.30 for my farmer.

**Comment by Qwinn1** [comment]
Actually, wow, even 1.2.30 is failing now. 

```qwinn@Muninn:~/forktools$ forkstart apple -fnw
'forkstart apple -fnw' initiated on Sat 09 Oct 2021 05:09:20 PM EDT...

forkstart:  Attempting to run 'apple start farmer-no-wallet -r'
apple_harvester: stopped
apple_harvester: started
apple_farmer: started
apple_full_node: Traceback (most recent call last):
  File "/home/qwinn/apple-blockchain/venv/bin/apple_farmer", line 33, in <module>
    sys.exit(load_entry_point('apple-blockchain', 'console_scripts', 'apple_farmer')())
  File "/home/qwinn/apple-blockchain/apple/server/start_farmer.py", line 63, in main
    kwargs = service_kwargs_for_farmer(DEFAULT_ROOT_PATH, config, config_pool, keychain, DEFAULT_CONSTANTS)
  File "/home/qwinn/apple-blockchain/apple/server/start_farmer.py", line 38, in service_kwargs_for_farmer
    farmer = Farmer(root_path, config, config_pool, keychain, consensus_constants=updated_constants)
  File "/home/qwinn/apple-blockchain/apple/farmer/farmer.py", line 125, in __init__
    self.farmer_target = decode_puzzle_hash(self.farmer_target_encoded)
  File "/home/qwinn/apple-blockchain/apple/util/bech32m.py", line 114, in decode_puzzle_hash
    hrpgot, data = bech32_decode(address)
  File "/home/qwinn/apple-blockchain/apple/util/bech32m.py", line 70, in bech32_decode
    if (any(ord(x) < 33 or ord(x) > 126 for x in bech)) or (bech.lower() != bech and bech.upper() != bech):
TypeError: 'NoneType' object is not iterable
stopped
apple_full_node: started
qwinn@Muninn:~/forktools$ 
```

**Comment by Motko222** [comment]
Same problem in Debian - "MAC check failed". 1.2.30 works ok.

**Comment by Qwinn1** [comment]
Okay, I figured out what that was.  Because the `apple init` is failing, the target addresses it set in the config.yaml were null.  When I fixed that, I was able to start with 1.2.30.

**Comment by Qwinn1** [comment]
I discovered a way to get 1.2.90 working.

1)  Install 1.2.30.
2)  Delete plot key (and any others you may have) with `apple keys delete`
3)  Update to 1.2.90
4)  Add plot key back in.

Explains why harvester updates work fine.  No keys on those.

**Comment by ariegrossman** [comment]
I'm having the same issue installing 1.2.90 on ubuntu 20.04. Going to try to install 1.2.30 first.
